import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shadcn/app-sidebar";
import { Separator } from "@radix-ui/react-separator";
import { ThemeProvider } from "@/components/shadcn/theme-provider"
import ThemeToggle from '../components/themeToggle';
import { NavGroup } from "@/interfaces/navbar.interface";
import { Footer } from '../components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const data:NavGroup[] = [
  {
    title: "Gestor Apis",
    url: "",
    items: [
      {
        title: "All",
        url: "/gestor-apis/all"
      },
      {
        title: "Apis Relevantes",
        url: ""
      },
      {
        title: "Búsqueda Global + Filtros",
        url: ""
      },
      {
        title: "Charts",
        url: ""
      },
    ]
  },
  {
    title: "Actions",
    url: ""
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
              <AppSidebar
                data={data}
              />
              <SidebarInset>
                <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
                  <SidebarTrigger className="-ml-1" />
                  <Separator
                    orientation="vertical"
                    className="mr-2 data-[orientation=vertical]:h-4"
                  />
                  <div className="ml-auto">
                    <ThemeToggle />
                  </div>
                </header>
                <div className="flex flex-col flex-1">
                  <div className="flex-1">
                    {children}
                  </div>
                  <footer className="w-full flex justify-end shrink-0 px-3">
                    <Footer />
                  </footer>
                </div>
              </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
